server {
    listen 80;
    server_name localhost;

    location /tuberculosis {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /tuberculosis/index.html;
    }

    location / {
        return 301 $scheme://$server_name/tuberculosis;
    }
}
